import { SupportedDevicesResponse } from "./api";

export const mockSupportedDevices: SupportedDevicesResponse = {
  data: [
    {
      type: "Smartphones",
      manufacturers: [
        {
          manufacturer: "iPhone",
          devices: [
            { id: "1", device: "iPhone 17 Pro Max" },
            { id: "2", device: "iPhone 17 Pro" },
            { id: "3", device: "iPhone 17 Air" },
            { id: "4", device: "iPhone 17" },
            { id: "5", device: "iPhone 16e" },
            { id: "6", device: "iPhone 16 Pro Max" },
            { id: "7", device: "iPhone 16 Plus" },
            { id: "8", device: "iPhone 16 Pro" },
            { id: "9", device: "iPhone 16" },
            { id: "10", device: "iPhone 15 Pro Max" },
            { id: "11", device: "iPhone 15 Plus" },
            { id: "12", device: "iPhone 15 Pro" },
            { id: "13", device: "iPhone 15" },
            { id: "14", device: "iPhone 14 Pro Max" },
            { id: "15", device: "iPhone 14 Plus" },
            { id: "16", device: "iPhone 14 Pro" },
            { id: "17", device: "iPhone 14" },
            { id: "18", device: "iPhone SE 3 (2022)" },
            { id: "19", device: "iPhone 13 Pro Max" },
            { id: "20", device: "iPhone 13 Pro" },
            { id: "21", device: "iPhone 13 Mini" },
            { id: "22", device: "iPhone 13" },
            { id: "23", device: "iPhone 12 Pro Max" },
            { id: "24", device: "iPhone 12 Pro" },
            { id: "25", device: "iPhone 12 Mini" },
            { id: "26", device: "iPhone 12" },
            { id: "27", device: "iPhone SE 2 (2020)" },
            { id: "28", device: "iPhone 11 Pro Max" },
            { id: "29", device: "iPhone 11 Pro" },
            { id: "30", device: "iPhone 11" },
            { id: "31", device: "iPhone XS Max" },
            { id: "32", device: "iPhone XS" },
            { id: "33", device: "iPhone XR" },
          ],
        },
        {
          manufacturer: "Samsung",
          devices: [
            { id: "34", device: "Samsung Galaxy Z TriFold" },
            { id: "35", device: "Samsung Galaxy A17" },
            { id: "36", device: "Samsung Galaxy XCover7 Pro" },
            { id: "37", device: "Samsung Galaxy A56" },
            { id: "38", device: "Samsung Galaxy A55 5G" },
            { id: "39", device: "Samsung Galaxy A54 5G" },
            { id: "40", device: "Samsung Galaxy A36" },
            { id: "41", device: "Samsung Galaxy A35 5G" },
            { id: "42", device: "Samsung Galaxy A23 5G" },
            { id: "43", device: "Samsung Galaxy Z Flip5" },
            { id: "44", device: "Samsung Galaxy Z Flip6" },
            { id: "45", device: "Samsung Galaxy Z Flip 7" },
            { id: "46", device: "Samsung Galaxy Z Fold" },
            { id: "47", device: "Samsung Galaxy Z Fold3" },
            { id: "48", device: "Samsung Galaxy Z Fold5" },
            { id: "49", device: "Samsung Galaxy Z Fold6" },
            { id: "50", device: "Samsung Galaxy Z Fold7" },
            { id: "51", device: "Samsung Galaxy S25" },
            { id: "52", device: "Samsung Galaxy S25 Edge" },
            { id: "53", device: "Samsung Galaxy S25+" },
            { id: "54", device: "Samsung Galaxy S25 Ultra" },
            { id: "55", device: "Samsung Galaxy S24 Ultra" },
            { id: "56", device: "Samsung Galaxy S24+" },
            { id: "57", device: "Samsung Galaxy S24 FE" },
            { id: "58", device: "Samsung Galaxy S24" },
            { id: "59", device: "Samsung Galaxy S23 Ultra" },
            { id: "60", device: "Samsung Galaxy S23+" },
            { id: "61", device: "Samsung Galaxy S23 5G" },
            { id: "62", device: "Samsung Galaxy S22 Ultra 5G" },
            { id: "63", device: "Samsung Galaxy S22+ 5G" },
            { id: "64", device: "Samsung Galaxy S22 5G" },
            { id: "65", device: "Samsung Galaxy S21 Ultra 5G" },
            { id: "66", device: "Samsung Galaxy S21+ 5G" },
            { id: "67", device: "Samsung Galaxy S21 5G" },
            { id: "68", device: "Samsung Galaxy S20 Ultra 5G" },
            { id: "69", device: "Samsung Galaxy S20+ 5G" },
            { id: "70", device: "Samsung Galaxy S20 5G" },
          ],
        },
        {
          manufacturer: "Google",
          devices: [
            { id: "71", device: "Google Pixel 10 Pro Fold" },
            { id: "72", device: "Google Pixel 10 Pro XL" },
            { id: "73", device: "Google Pixel 10 Pro" },
            { id: "74", device: "Google Pixel 10" },
            { id: "75", device: "Google Pixel 9 Pro Fold" },
            { id: "76", device: "Google Pixel 9 Pro XL" },
            { id: "77", device: "Google Pixel 9 Pro" },
            { id: "78", device: "Google Pixel 9" },
            { id: "79", device: "Google Pixel 9a" },
            { id: "80", device: "Google Pixel Fold" },
            { id: "81", device: "Google Pixel 8 Pro" },
            { id: "82", device: "Google Pixel 8" },
            { id: "83", device: "Google Pixel 8a" },
            { id: "84", device: "Google Pixel 7 Pro" },
            { id: "85", device: "Google Pixel 7" },
            { id: "86", device: "Google Pixel 7a" },
            { id: "87", device: "Google Pixel 6 Pro" },
            { id: "88", device: "Google pixel 6a" },
            { id: "89", device: "Google Pixel 6" },
            { id: "90", device: "Google Pixel 5a 5G" },
            { id: "91", device: "Google Pixel 5" },
            { id: "92", device: "Google Pixel 4 XL" },
            { id: "93", device: "Google Pixel 4a 5G" },
            { id: "94", device: "Google Pixel 4" },
            { id: "95", device: "Google Pixel 3a XL" },
            { id: "96", device: "Google Pixel 3a" },
            { id: "97", device: "Google Pixel 3 XL" },
            { id: "98", device: "Google Pixel 3" },
            { id: "99", device: "Google Pixel 2 XL" },
            { id: "100", device: "Google Pixel 2" },
          ],
        },
        {
          manufacturer: "Huawei",
          devices: [
            { id: "101", device: "Huawei Mate 40 Pro" },
            { id: "102", device: "Huawei P40 Pro" },
            { id: "103", device: "Huawei P40" },
            { id: "104", device: "Huawei 80 Pro / Pro+ / Ultra" },
            { id: "105", device: "Huawei Pura 70 Pro" },
            { id: "106", device: "Pura X foldable" },
          ],
        },
        {
          manufacturer: "Xiaomi",
          devices: [
            { id: "107", device: "Xiaomi 15T Pro" },
            { id: "108", device: "Xiaomi 15T" },
            { id: "109", device: "Xiaomi 15" },
            { id: "110", device: "Xiaomi 15 Ultra" },
            { id: "111", device: "Xiaomi 14" },
            { id: "112", device: "Xiaomi 14 Pro" },
            { id: "113", device: "Xiaomi 14T" },
            { id: "114", device: "Xiaomi 14T Pro" },
            { id: "115", device: "Xiaomi 13T" },
            { id: "116", device: "Xiaomi 13T Pro" },
            { id: "117", device: "Xiaomi 13 Pro" },
            { id: "118", device: "Xiaomi 13 Lite" },
            { id: "119", device: "Xiaomi 13" },
            { id: "120", device: "Xiaomi 12T Pro" },
          ],
        },
        {
          manufacturer: "Motorola",
          devices: [
            { id: "121", device: "Motorola Razr (2025)" },
            { id: "122", device: "Motorola Razr+ (2025)" },
            { id: "123", device: "Motorola Razr Ultra (2025)" },
            { id: "124", device: "Motorola Razr+" },
            { id: "125", device: "Motorola Razr Fold" },
            { id: "126", device: "Motorola G52J 5G" },
            { id: "127", device: "Motorola G53J 5G" },
            { id: "128", device: "Motorola Moto G34" },
            { id: "129", device: "Motorola Moto G35" },
            { id: "130", device: "Motorola Moto G54" },
            { id: "131", device: "Motorola Moto G55" },
            { id: "132", device: "Motorola Moto G75" },
            { id: "133", device: "Motorola Moto G84" },
            { id: "134", device: "Motorola Moto G85" },
            { id: "135", device: "Motorola Edge 50" },
            { id: "136", device: "Motorola Edge 50 Fusion" },
            { id: "137", device: "Motorola Edge 50 Pro" },
          ],
        },
      ],
    },
    {
      type: "Smartwatches",
      manufacturers: [
        {
          manufacturer: "Apple",
          devices: [
            { id: "138", device: "Apple Watch Series 9" },
            { id: "139", device: "Apple Watch Series 8" },
            { id: "140", device: "Apple Watch Series 7" },
            { id: "141", device: "Apple Watch Series 6" },
            { id: "142", device: "Apple Watch Series 5" },
            { id: "143", device: "Apple Watch Series 4" },
            { id: "144", device: "Apple Watch Ultra 2" },
            { id: "145", device: "Apple Watch Ultra" },
            { id: "146", device: "Apple Watch SE (2nd gen)" },
            { id: "147", device: "Apple Watch SE (1st gen)" },
          ],
        },
        {
          manufacturer: "Samsung",
          devices: [
            { id: "148", device: "Samsung Galaxy Watch 6" },
            { id: "149", device: "Samsung Galaxy Watch 5" },
            { id: "150", device: "Samsung Galaxy Watch 4" },
          ],
        },
      ],
    },
    {
      type: "Tablets",
      manufacturers: [
        {
          manufacturer: "Apple",
          devices: [
            { id: "151", device: "iPad Pro 12.9-inch (3rd gen and later)" },
            { id: "152", device: "iPad Pro 11-inch (all models)" },
            { id: "153", device: "iPad Air (3rd gen and later)" },
            { id: "154", device: "iPad (7th gen and later)" },
            { id: "155", device: "iPad Mini (5th gen and later)" },
          ],
        },
        {
          manufacturer: "Samsung",
          devices: [
            { id: "156", device: "Samsung Galaxy Tab S9" },
            { id: "157", device: "Samsung Galaxy Tab S8" },
            { id: "158", device: "Samsung Galaxy Tab S7" },
          ],
        },
      ],
    },
    {
      type: "Laptops",
      manufacturers: [
        {
          manufacturer: "Microsoft",
          devices: [
            { id: "159", device: "Surface Pro 9 with 5G" },
            { id: "160", device: "Surface Pro X" },
            { id: "161", device: "Surface Go 3" },
          ],
        },
        {
          manufacturer: "Lenovo",
          devices: [
            { id: "162", device: "Lenovo ThinkPad X1 Carbon Gen 11" },
            { id: "163", device: "Lenovo Yoga 9i" },
          ],
        },
      ],
    },
  ],
};
